### ISSUE TITLE
Allow changing the FTP port and Add authentication

### ISSUE THREAD

**Issue by fennectech** [devnoname120/vitacompanion#9]
This tool could use authentication and the ability to change the port would be nice to have but auth for something we keep running is a must.

**Comment by devnoname120** [comment]
This is a tool for developers, if you want to change the port just change it and recompile! :)

About FTP authentication, it's unfortunately [not implemented](https://github.com/xerpi/libftpvita/blob/e37a3c08b499854c9a5b138d1bcdf54af564fdac/libftpvita/ftpvita.c#L140-L148) and I'm not interested in implementing authentication for the command server. This would introduce increased complexity and I don't have this need since I always use vitacompanion behind a NAT.
